local sysname = vim.loop.os_uname().sysname

return {
  'neovim/nvim-lspconfig',
  'tpope/vim-fugitive',
  'ludovicchabant/vim-lawrencium',
  'airblade/vim-gitgutter',
  'folke/trouble.nvim',
  'hashivim/vim-terraform',
  'nvim-tree/nvim-web-devicons',
  'sindrets/diffview.nvim',
  'ms-jpq/coq_nvim',
  'ms-jpq/coq.artifacts',
  'ms-jpq/coq.thirdparty',
  'mfussenegger/nvim-dap',
  'rcarriga/nvim-dap-ui',
  'folke/neodev.nvim',
  'leoluz/nvim-dap-go',
  'nvim-neotest/nvim-nio',
  'github/copilot.vim',
  'nvim-neotest/neotest',
  'fredrikaverpil/neotest-golang',
  'olimorris/codecompanion.nvim',
  'echasnovski/mini.diff',
}
