require("dapui").setup()
require('dap-go').setup()

vim.keymap.set("n", "<Leader>du", "<cmd>lua require('dapui').toggle()<CR>")

vim.keymap.set("n", "<Leader>dt", "<cmd>lua require('dap-go').debug_test()<CR>")
vim.keymap.set('n', '<F5>', function() require('dap').continue() end, { desc = "Start/Continue Debugging" })
vim.keymap.set('n', '<F10>', function() require('dap').step_over() end, { desc = "[dap] Step Over" })
vim.keymap.set('n', '<F11>', function() require('dap').step_into() end, { desc = "[dap] Step Into" })
vim.keymap.set('n', '<F12>', function() require('dap').step_out() end, { desc = "[dap] Step Out" })
vim.keymap.set('n', '<Leader>b', function() require('dap').toggle_breakpoint() end, { desc = "[dap] Toggle Breakpoint" })
vim.keymap.set('n', '<Leader>B', function() require('dap').set_breakpoint() end, { desc = "[dap] Set Breakpoint" })
vim.keymap.set('n', '<Leader>lp', function() require('dap').set_breakpoint(nil, nil, vim.fn.input('Log point message: ')) end, { desc = "[dap] Set Logpoint" })
vim.keymap.set('n', '<Leader>dr', function() require('dap').repl.open() end, { desc = "[dap] Open REPL" })
vim.keymap.set('n', '<Leader>dl', function() require('dap').run_last() end, { desc = "[dap] Run Last" })
vim.keymap.set('n', '<Leader>do', function() require('dapui').open() end, { desc = "[dap ui] Open UI" })
vim.keymap.set('n', '<Leader>dc', function() require('dapui').close() end, { desc = "[dap ui] Close UI" })
vim.keymap.set({'n', 'v'}, '<Leader>dh', function()
  require('dap.ui.widgets').hover()
end, { desc = "[dap ui] Hover" })
vim.keymap.set({'n', 'v'}, '<Leader>dp', function()
  require('dap.ui.widgets').preview()
end, { desc = "[dap ui] Preview" })
vim.keymap.set('n', '<Leader>df', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.frames)
end, { desc = "[dap ui] Show Frames" })
vim.keymap.set('n', '<Leader>ds', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.scopes)
end, { desc = "[dap ui] Show Scopes" })
