return {
  'tpope/vim-fugitive',
  'ludovicchabant/vim-lawrencium',
  'airblade/vim-gitgutter',
  'hashivim/vim-terraform',
  'nvim-tree/nvim-web-devicons',
  'sindrets/diffview.nvim',
  'fredrikaverpil/neotest-golang',
  'nvim-neotest/nvim-nio',
  { 'folke/which-key.nvim',                  config = true },
  { 'echasnovski/mini.diff',                 config = true },
  { import = "overlays.50_dev.lspconfig" },
  { import = "overlays.50_dev.trouble" },
  { import = "overlays.50_dev.blink" },
  { import = "overlays.50_dev.neotest" },
  { import = "overlays.50_dev.copilot" },
  { import = "overlays.50_dev.codecompanion" },
  { import = "overlays.50_dev.dap" },
  { 'folke/lazydev.nvim',                    config = true },
}
