- name: "install go - mac"
  homebrew:
    name: go
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: "install golang - archlinux"
  pacman:
    name: go
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: "install gopls - mac"
  homebrew:
    name: gopls
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: "install gopls - archlinux"
  pacman:
    name: gopls
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: "add golang backports ppa - ubuntu"
  apt_repository:
    repo: "ppa:longsleep/golang-backports"
    state: "present"
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: "install golang-go - ubuntu"
  apt:
    name: golang-go
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: "Install gopls - ubuntu"
  command: go install golang.org/x/tools/gopls@latest
  args:
    # Prevent re-running if the binary already exists
    creates: "{{ ansible_env.HOME }}/go/bin/gopls"
