- name: "install go - mac"
  fail:
    msg: "Implement this - not on macbook when this was written"
  when: ansible_distribution == 'MacOSX'

- name: "install golang - archlinux"
  pacman:
    name: go
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: "install gopls - archlinux"
  pacman:
    name: gopls
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: "add golang backports ppa - ubuntu"
  apt_repository:
    repo: "ppa:longsleep/golang-backports"
    state: "present"
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: "install golang-go - ubuntu"
  apt:
    name: golang-go
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'
