- name: "install zsh - mac"
  homebrew:
    name: zsh
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: "install zsh - archlinux"
  pacman:
    name: zsh
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: "install zsh - ubuntu"
  apt:
    name: zsh
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: "install starship"
  shell:
    cmd: "curl -sS https://starship.rs/install.sh | sh -s -- --yes"
  become: true

- name: "install zoxide"
  shell:
    cmd: "curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh"
